- hosts: all
  gather_facts: True
  become: yes
  tasks:
    - package:
        name:
          - pandoc
          - flex
          - bison
          - screen
          - readline-devel
          - aspell
          - poppler-utils
          - net-tools
          - wget
          - git
          - python3-pip
          - psmisc
          - rsync
          - tidy
          - lynx
          - telnet
          - emacs
          - subversion
          - m4 
          - latexmk
          - libpq-devel
          - automake 
          - jq
          - gfortran 
          - openssl-devel
          - cairo-devel
          - graphviz
          - octave
          - smem
          - python3-psycopg2
          - postgresql-server 
          - postgresql-contrib
          - clang-tools-extra
          - golang 
          - R-formatR
          - yasm
          - sage
          - sagemath
          - sagemath-sagetex
          - python3-yaml   
          - python3-matplotlib  
          - python3-ipywidgets 
          - python3-jupyter-core
          - sagemath-jupyter
          - python3-metakernel
          - python3-metakernel-python.noarch
          - python3-nbconvert.noarch
          - python3-nbformat.noarch
          - python3-octave-kernel
          - nodejs
          - libxml2-devel
          - libxslt-devel
          - julia
          - R-core-devel     
          - zeromq-devel 
          - curl-devel
          - xorg-x11-server-Xvfb
          - xsel
          - novnc 
          - python3-websockify
          - curl 
          - xpra
          - xorg-x11-apps
          - dbus-x11
          - gnome-terminal
          - vim-X11
          - lyx 
          - libreoffice 
          - inkscape 
          - gimp 
          - firefox 
          - texstudio 
          - evince
          - glx-utils
          - xdotool
          - xclip
          - setxkbmap
          - texlive-pythontex
          - python3-yapf
        state: present

